apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dind-internet-only
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: gimmelinux-dind
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 127.0.0.0/8

    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53